### PR TITLE
docs: fix License url

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by popomore** [comment]
https://github.com/eggjs/egg/pull/989

**Comment by fengmk2** [comment]
ci 挂了

image

**Comment by atian25** [comment]
先合了，ci 看另一个 PR

**Comment by popomore** [comment]
这个应该是 onerror 改回来后的错吧。

**Comment by popomore** [comment]
我先发个版本

**Pull request merged**
