### PR TITLE
feat: [BREAKING_CHANGE] use loader.getLoadUnits from egg-core

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

None

##### Description of change

egg-core 重构后，使用 loader 新的 API getLoadUnits

### CODE REVIEW

**Comment by popomore** [comment]
这个要发大版本？都 1.0 了

**Comment by atian25** [comment]
感觉用 setTimeout 这里时间不精确，用例好像有点不稳定，有时会多一个少一个。

+1

**Comment by fengmk2** [comment]
发 patch 就好

**Comment by fengmk2** [comment]
1.1.1

**Pull request merged**
